// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WarehouseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseInfo) Reset() {
	*x = WarehouseInfo{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseInfo) ProtoMessage() {}

func (x *WarehouseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseInfo.ProtoReflect.Descriptor instead.
func (*WarehouseInfo) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *WarehouseInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WarehouseInfo) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseInfo []*WarehouseInfo       `protobuf:"bytes,2,rep,name=warehouse_info,json=warehouseInfo,proto3" json:"warehouse_info,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProductRequest) GetWarehouseInfo() []*WarehouseInfo {
	if x != nil {
		return x.WarehouseInfo
	}
	return nil
}

func (x *AddProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

type WarehouseExistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseExistReq) Reset() {
	*x = WarehouseExistReq{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseExistReq) ProtoMessage() {}

func (x *WarehouseExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseExistReq.ProtoReflect.Descriptor instead.
func (*WarehouseExistReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

type WarehouseExistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseExistResp) Reset() {
	*x = WarehouseExistResp{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseExistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseExistResp) ProtoMessage() {}

func (x *WarehouseExistResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseExistResp.ProtoReflect.Descriptor instead.
func (*WarehouseExistResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *WarehouseExistResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type ListWarehousesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesReq) Reset() {
	*x = ListWarehousesReq{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesReq) ProtoMessage() {}

func (x *ListWarehousesReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesReq.ProtoReflect.Descriptor instead.
func (*ListWarehousesReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

type ListWarehousesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warehouses    []*Warehouse           `protobuf:"bytes,1,rep,name=warehouses,proto3" json:"warehouses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWarehousesResp) Reset() {
	*x = ListWarehousesResp{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWarehousesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWarehousesResp) ProtoMessage() {}

func (x *ListWarehousesResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWarehousesResp.ProtoReflect.Descriptor instead.
func (*ListWarehousesResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ListWarehousesResp) GetWarehouses() []*Warehouse {
	if x != nil {
		return x.Warehouses
	}
	return nil
}

type Warehouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	StateId       uint32                 `protobuf:"varint,6,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CountryId     uint32                 `protobuf:"varint,7,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warehouse) Reset() {
	*x = Warehouse{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warehouse) ProtoMessage() {}

func (x *Warehouse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warehouse.ProtoReflect.Descriptor instead.
func (*Warehouse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *Warehouse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warehouse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Warehouse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Warehouse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Warehouse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Warehouse) GetStateId() uint32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *Warehouse) GetCountryId() uint32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *Warehouse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Warehouse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Warehouse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateWarehouseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	StateId       uint32                 `protobuf:"varint,5,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	CountryId     uint32                 `protobuf:"varint,6,opt,name=country_id,json=countryId,proto3" json:"country_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseReq) Reset() {
	*x = CreateWarehouseReq{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseReq) ProtoMessage() {}

func (x *CreateWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseReq.ProtoReflect.Descriptor instead.
func (*CreateWarehouseReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWarehouseReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateWarehouseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWarehouseReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateWarehouseReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateWarehouseReq) GetStateId() uint32 {
	if x != nil {
		return x.StateId
	}
	return 0
}

func (x *CreateWarehouseReq) GetCountryId() uint32 {
	if x != nil {
		return x.CountryId
	}
	return 0
}

func (x *CreateWarehouseReq) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateWarehouseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWarehouseResp) Reset() {
	*x = CreateWarehouseResp{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWarehouseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWarehouseResp) ProtoMessage() {}

func (x *CreateWarehouseResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWarehouseResp.ProtoReflect.Descriptor instead.
func (*CreateWarehouseResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *CreateWarehouseResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteWarehouseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseIds  []uint32               `protobuf:"varint,1,rep,packed,name=warehouse_ids,json=warehouseIds,proto3" json:"warehouse_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseReq) Reset() {
	*x = DeleteWarehouseReq{}
	mi := &file_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseReq) ProtoMessage() {}

func (x *DeleteWarehouseReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseReq.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWarehouseReq) GetWarehouseIds() []uint32 {
	if x != nil {
		return x.WarehouseIds
	}
	return nil
}

type DeleteWarehouseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWarehouseResp) Reset() {
	*x = DeleteWarehouseResp{}
	mi := &file_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWarehouseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWarehouseResp) ProtoMessage() {}

func (x *DeleteWarehouseResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWarehouseResp.ProtoReflect.Descriptor instead.
func (*DeleteWarehouseResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{11}
}

type CreateStockMovementReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   uint32                 `protobuf:"varint,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	WarehouseId   uint32                 `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	MovementType  string                 `protobuf:"bytes,4,opt,name=movement_type,json=movementType,proto3" json:"movement_type,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reference     string                 `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockMovementReq) Reset() {
	*x = CreateStockMovementReq{}
	mi := &file_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockMovementReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockMovementReq) ProtoMessage() {}

func (x *CreateStockMovementReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockMovementReq.ProtoReflect.Descriptor instead.
func (*CreateStockMovementReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CreateStockMovementReq) GetInventoryId() uint32 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *CreateStockMovementReq) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateStockMovementReq) GetWarehouseId() uint32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *CreateStockMovementReq) GetMovementType() string {
	if x != nil {
		return x.MovementType
	}
	return ""
}

func (x *CreateStockMovementReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateStockMovementReq) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *CreateStockMovementReq) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateStockMovementReq) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateStockMovementResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockMovementResp) Reset() {
	*x = CreateStockMovementResp{}
	mi := &file_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockMovementResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockMovementResp) ProtoMessage() {}

func (x *CreateStockMovementResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockMovementResp.ProtoReflect.Descriptor instead.
func (*CreateStockMovementResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *CreateStockMovementResp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListStockMovementsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WarehouseId   uint32                 `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStockMovementsReq) Reset() {
	*x = ListStockMovementsReq{}
	mi := &file_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStockMovementsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStockMovementsReq) ProtoMessage() {}

func (x *ListStockMovementsReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStockMovementsReq.ProtoReflect.Descriptor instead.
func (*ListStockMovementsReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *ListStockMovementsReq) GetWarehouseId() uint32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *ListStockMovementsReq) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type ListStockMovementsResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StockMovements []*StockMovement       `protobuf:"bytes,1,rep,name=stock_movements,json=stockMovements,proto3" json:"stock_movements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStockMovementsResp) Reset() {
	*x = ListStockMovementsResp{}
	mi := &file_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStockMovementsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStockMovementsResp) ProtoMessage() {}

func (x *ListStockMovementsResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStockMovementsResp.ProtoReflect.Descriptor instead.
func (*ListStockMovementsResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *ListStockMovementsResp) GetStockMovements() []*StockMovement {
	if x != nil {
		return x.StockMovements
	}
	return nil
}

type StockMovement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InventoryId   uint32                 `protobuf:"varint,2,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	WarehouseId   uint32                 `protobuf:"varint,4,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	MovementType  string                 `protobuf:"bytes,5,opt,name=movement_type,json=movementType,proto3" json:"movement_type,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reference     string                 `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockMovement) Reset() {
	*x = StockMovement{}
	mi := &file_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockMovement) ProtoMessage() {}

func (x *StockMovement) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockMovement.ProtoReflect.Descriptor instead.
func (*StockMovement) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *StockMovement) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockMovement) GetInventoryId() uint32 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *StockMovement) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *StockMovement) GetWarehouseId() uint32 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *StockMovement) GetMovementType() string {
	if x != nil {
		return x.MovementType
	}
	return ""
}

func (x *StockMovement) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockMovement) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *StockMovement) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *StockMovement) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *StockMovement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\finventory.v1\";\n" +
	"\rWarehouseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\x88\x01\n" +
	"\x11AddProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12B\n" +
	"\x0ewarehouse_info\x18\x02 \x03(\v2\x1b.inventory.v1.WarehouseInfoR\rwarehouseInfo\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"\x14\n" +
	"\x12AddProductResponse\"\x13\n" +
	"\x11WarehouseExistReq\",\n" +
	"\x12WarehouseExistResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x13\n" +
	"\x11ListWarehousesReq\"M\n" +
	"\x12ListWarehousesResp\x127\n" +
	"\n" +
	"warehouses\x18\x01 \x03(\v2\x17.inventory.v1.WarehouseR\n" +
	"warehouses\"\x86\x02\n" +
	"\tWarehouse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x19\n" +
	"\bstate_id\x18\x06 \x01(\rR\astateId\x12\x1d\n" +
	"\n" +
	"country_id\x18\a \x01(\rR\tcountryId\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xc1\x01\n" +
	"\x12CreateWarehouseReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x19\n" +
	"\bstate_id\x18\x05 \x01(\rR\astateId\x12\x1d\n" +
	"\n" +
	"country_id\x18\x06 \x01(\rR\tcountryId\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"%\n" +
	"\x13CreateWarehouseResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"9\n" +
	"\x12DeleteWarehouseReq\x12#\n" +
	"\rwarehouse_ids\x18\x01 \x03(\rR\fwarehouseIds\"\x15\n" +
	"\x13DeleteWarehouseResp\"\x84\x02\n" +
	"\x16CreateStockMovementReq\x12!\n" +
	"\finventory_id\x18\x01 \x01(\rR\vinventoryId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\rR\vwarehouseId\x12#\n" +
	"\rmovement_type\x18\x04 \x01(\tR\fmovementType\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x1c\n" +
	"\treference\x18\x06 \x01(\tR\treference\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\rR\tcreatedBy\")\n" +
	"\x17CreateStockMovementResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"L\n" +
	"\x15ListStockMovementsReq\x12!\n" +
	"\fwarehouse_id\x18\x01 \x01(\rR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\"^\n" +
	"\x16ListStockMovementsResp\x12D\n" +
	"\x0fstock_movements\x18\x01 \x03(\v2\x1b.inventory.v1.StockMovementR\x0estockMovements\"\xaa\x02\n" +
	"\rStockMovement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\finventory_id\x18\x02 \x01(\rR\vinventoryId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12!\n" +
	"\fwarehouse_id\x18\x04 \x01(\rR\vwarehouseId\x12#\n" +
	"\rmovement_type\x18\x05 \x01(\tR\fmovementType\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x1c\n" +
	"\treference\x18\a \x01(\tR\treference\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt2\x8c\x05\n" +
	"\x10InventoryService\x12X\n" +
	"\x13CreateProductRecord\x12\x1f.inventory.v1.AddProductRequest\x1a .inventory.v1.AddProductResponse\x12T\n" +
	"\x0fHasAnyWarehouse\x12\x1f.inventory.v1.WarehouseExistReq\x1a .inventory.v1.WarehouseExistResp\x12S\n" +
	"\x0eListWarehouses\x12\x1f.inventory.v1.ListWarehousesReq\x1a .inventory.v1.ListWarehousesResp\x12V\n" +
	"\x0fCreateWarehouse\x12 .inventory.v1.CreateWarehouseReq\x1a!.inventory.v1.CreateWarehouseResp\x12V\n" +
	"\x0fDeleteWarehouse\x12 .inventory.v1.DeleteWarehouseReq\x1a!.inventory.v1.DeleteWarehouseResp\x12b\n" +
	"\x13CreateStockMovement\x12$.inventory.v1.CreateStockMovementReq\x1a%.inventory.v1.CreateStockMovementResp\x12_\n" +
	"\x12ListStockMovements\x12#.inventory.v1.ListStockMovementsReq\x1a$.inventory.v1.ListStockMovementsRespB;Z9github.com/chibx/vuecom/backend/shared/proto/go/inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_inventory_proto_goTypes = []any{
	(*WarehouseInfo)(nil),           // 0: inventory.v1.WarehouseInfo
	(*AddProductRequest)(nil),       // 1: inventory.v1.AddProductRequest
	(*AddProductResponse)(nil),      // 2: inventory.v1.AddProductResponse
	(*WarehouseExistReq)(nil),       // 3: inventory.v1.WarehouseExistReq
	(*WarehouseExistResp)(nil),      // 4: inventory.v1.WarehouseExistResp
	(*ListWarehousesReq)(nil),       // 5: inventory.v1.ListWarehousesReq
	(*ListWarehousesResp)(nil),      // 6: inventory.v1.ListWarehousesResp
	(*Warehouse)(nil),               // 7: inventory.v1.Warehouse
	(*CreateWarehouseReq)(nil),      // 8: inventory.v1.CreateWarehouseReq
	(*CreateWarehouseResp)(nil),     // 9: inventory.v1.CreateWarehouseResp
	(*DeleteWarehouseReq)(nil),      // 10: inventory.v1.DeleteWarehouseReq
	(*DeleteWarehouseResp)(nil),     // 11: inventory.v1.DeleteWarehouseResp
	(*CreateStockMovementReq)(nil),  // 12: inventory.v1.CreateStockMovementReq
	(*CreateStockMovementResp)(nil), // 13: inventory.v1.CreateStockMovementResp
	(*ListStockMovementsReq)(nil),   // 14: inventory.v1.ListStockMovementsReq
	(*ListStockMovementsResp)(nil),  // 15: inventory.v1.ListStockMovementsResp
	(*StockMovement)(nil),           // 16: inventory.v1.StockMovement
}
var file_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.AddProductRequest.warehouse_info:type_name -> inventory.v1.WarehouseInfo
	7,  // 1: inventory.v1.ListWarehousesResp.warehouses:type_name -> inventory.v1.Warehouse
	16, // 2: inventory.v1.ListStockMovementsResp.stock_movements:type_name -> inventory.v1.StockMovement
	1,  // 3: inventory.v1.InventoryService.CreateProductRecord:input_type -> inventory.v1.AddProductRequest
	3,  // 4: inventory.v1.InventoryService.HasAnyWarehouse:input_type -> inventory.v1.WarehouseExistReq
	5,  // 5: inventory.v1.InventoryService.ListWarehouses:input_type -> inventory.v1.ListWarehousesReq
	8,  // 6: inventory.v1.InventoryService.CreateWarehouse:input_type -> inventory.v1.CreateWarehouseReq
	10, // 7: inventory.v1.InventoryService.DeleteWarehouse:input_type -> inventory.v1.DeleteWarehouseReq
	12, // 8: inventory.v1.InventoryService.CreateStockMovement:input_type -> inventory.v1.CreateStockMovementReq
	14, // 9: inventory.v1.InventoryService.ListStockMovements:input_type -> inventory.v1.ListStockMovementsReq
	2,  // 10: inventory.v1.InventoryService.CreateProductRecord:output_type -> inventory.v1.AddProductResponse
	4,  // 11: inventory.v1.InventoryService.HasAnyWarehouse:output_type -> inventory.v1.WarehouseExistResp
	6,  // 12: inventory.v1.InventoryService.ListWarehouses:output_type -> inventory.v1.ListWarehousesResp
	9,  // 13: inventory.v1.InventoryService.CreateWarehouse:output_type -> inventory.v1.CreateWarehouseResp
	11, // 14: inventory.v1.InventoryService.DeleteWarehouse:output_type -> inventory.v1.DeleteWarehouseResp
	13, // 15: inventory.v1.InventoryService.CreateStockMovement:output_type -> inventory.v1.CreateStockMovementResp
	15, // 16: inventory.v1.InventoryService.ListStockMovements:output_type -> inventory.v1.ListStockMovementsResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
