// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_CreateProductRecord_FullMethodName = "/inventory.v1.InventoryService/CreateProductRecord"
	InventoryService_HasAnyWarehouse_FullMethodName     = "/inventory.v1.InventoryService/HasAnyWarehouse"
	InventoryService_ListWarehouses_FullMethodName      = "/inventory.v1.InventoryService/ListWarehouses"
	InventoryService_CreateWarehouse_FullMethodName     = "/inventory.v1.InventoryService/CreateWarehouse"
	InventoryService_DeleteWarehouse_FullMethodName     = "/inventory.v1.InventoryService/DeleteWarehouse"
	InventoryService_CreateStockMovement_FullMethodName = "/inventory.v1.InventoryService/CreateStockMovement"
	InventoryService_ListStockMovements_FullMethodName  = "/inventory.v1.InventoryService/ListStockMovements"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	// Add your service methods here
	CreateProductRecord(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
	HasAnyWarehouse(ctx context.Context, in *WarehouseExistReq, opts ...grpc.CallOption) (*WarehouseExistResp, error)
	ListWarehouses(ctx context.Context, in *ListWarehousesReq, opts ...grpc.CallOption) (*ListWarehousesResp, error)
	CreateWarehouse(ctx context.Context, in *CreateWarehouseReq, opts ...grpc.CallOption) (*CreateWarehouseResp, error)
	DeleteWarehouse(ctx context.Context, in *DeleteWarehouseReq, opts ...grpc.CallOption) (*DeleteWarehouseResp, error)
	CreateStockMovement(ctx context.Context, in *CreateStockMovementReq, opts ...grpc.CallOption) (*CreateStockMovementResp, error)
	ListStockMovements(ctx context.Context, in *ListStockMovementsReq, opts ...grpc.CallOption) (*ListStockMovementsResp, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) CreateProductRecord(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateProductRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) HasAnyWarehouse(ctx context.Context, in *WarehouseExistReq, opts ...grpc.CallOption) (*WarehouseExistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarehouseExistResp)
	err := c.cc.Invoke(ctx, InventoryService_HasAnyWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListWarehouses(ctx context.Context, in *ListWarehousesReq, opts ...grpc.CallOption) (*ListWarehousesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWarehousesResp)
	err := c.cc.Invoke(ctx, InventoryService_ListWarehouses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateWarehouse(ctx context.Context, in *CreateWarehouseReq, opts ...grpc.CallOption) (*CreateWarehouseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWarehouseResp)
	err := c.cc.Invoke(ctx, InventoryService_CreateWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) DeleteWarehouse(ctx context.Context, in *DeleteWarehouseReq, opts ...grpc.CallOption) (*DeleteWarehouseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWarehouseResp)
	err := c.cc.Invoke(ctx, InventoryService_DeleteWarehouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateStockMovement(ctx context.Context, in *CreateStockMovementReq, opts ...grpc.CallOption) (*CreateStockMovementResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStockMovementResp)
	err := c.cc.Invoke(ctx, InventoryService_CreateStockMovement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListStockMovements(ctx context.Context, in *ListStockMovementsReq, opts ...grpc.CallOption) (*ListStockMovementsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStockMovementsResp)
	err := c.cc.Invoke(ctx, InventoryService_ListStockMovements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
type InventoryServiceServer interface {
	// Add your service methods here
	CreateProductRecord(context.Context, *AddProductRequest) (*AddProductResponse, error)
	HasAnyWarehouse(context.Context, *WarehouseExistReq) (*WarehouseExistResp, error)
	ListWarehouses(context.Context, *ListWarehousesReq) (*ListWarehousesResp, error)
	CreateWarehouse(context.Context, *CreateWarehouseReq) (*CreateWarehouseResp, error)
	DeleteWarehouse(context.Context, *DeleteWarehouseReq) (*DeleteWarehouseResp, error)
	CreateStockMovement(context.Context, *CreateStockMovementReq) (*CreateStockMovementResp, error)
	ListStockMovements(context.Context, *ListStockMovementsReq) (*ListStockMovementsResp, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) CreateProductRecord(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProductRecord not implemented")
}
func (UnimplementedInventoryServiceServer) HasAnyWarehouse(context.Context, *WarehouseExistReq) (*WarehouseExistResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasAnyWarehouse not implemented")
}
func (UnimplementedInventoryServiceServer) ListWarehouses(context.Context, *ListWarehousesReq) (*ListWarehousesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWarehouses not implemented")
}
func (UnimplementedInventoryServiceServer) CreateWarehouse(context.Context, *CreateWarehouseReq) (*CreateWarehouseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWarehouse not implemented")
}
func (UnimplementedInventoryServiceServer) DeleteWarehouse(context.Context, *DeleteWarehouseReq) (*DeleteWarehouseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWarehouse not implemented")
}
func (UnimplementedInventoryServiceServer) CreateStockMovement(context.Context, *CreateStockMovementReq) (*CreateStockMovementResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStockMovement not implemented")
}
func (UnimplementedInventoryServiceServer) ListStockMovements(context.Context, *ListStockMovementsReq) (*ListStockMovementsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStockMovements not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_CreateProductRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateProductRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateProductRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateProductRecord(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_HasAnyWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarehouseExistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).HasAnyWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_HasAnyWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).HasAnyWarehouse(ctx, req.(*WarehouseExistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarehousesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListWarehouses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListWarehouses(ctx, req.(*ListWarehousesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateWarehouse(ctx, req.(*CreateWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_DeleteWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWarehouseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeleteWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeleteWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeleteWarehouse(ctx, req.(*DeleteWarehouseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateStockMovement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStockMovementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateStockMovement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateStockMovement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateStockMovement(ctx, req.(*CreateStockMovementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListStockMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStockMovementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListStockMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListStockMovements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListStockMovements(ctx, req.(*ListStockMovementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductRecord",
			Handler:    _InventoryService_CreateProductRecord_Handler,
		},
		{
			MethodName: "HasAnyWarehouse",
			Handler:    _InventoryService_HasAnyWarehouse_Handler,
		},
		{
			MethodName: "ListWarehouses",
			Handler:    _InventoryService_ListWarehouses_Handler,
		},
		{
			MethodName: "CreateWarehouse",
			Handler:    _InventoryService_CreateWarehouse_Handler,
		},
		{
			MethodName: "DeleteWarehouse",
			Handler:    _InventoryService_DeleteWarehouse_Handler,
		},
		{
			MethodName: "CreateStockMovement",
			Handler:    _InventoryService_CreateStockMovement_Handler,
		},
		{
			MethodName: "ListStockMovements",
			Handler:    _InventoryService_ListStockMovements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
