CREATE DATABASE catalog;
CREATE DATABASE orders;
CREATE DATABASE users;
CREATE DATABASE inventory;

CREATE USER vuecom;
GRANT ALL PRIVILEGES ON DATABASE catalog TO vuecom;
GRANT ALL PRIVILEGES ON DATABASE orders TO vuecom;
GRANT ALL PRIVILEGES ON DATABASE users TO vuecom;
GRANT ALL PRIVILEGES ON DATABASE inventory TO vuecom;