\c vuecom_catalog

-- GRANT CONNECT ON DATABASE vuecom_catalog TO vuecom;
-- GRANT ALL PRIVILEGES ON SCHEMA public TO vuecom;
-- GRANT ALL ON ALL TABLES IN SCHEMA public TO vuecom; 
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to vuecom;

\c vuecom_inventory

-- GRANT CONNECT ON DATABASE vuecom_inventory TO vuecom;
-- GRANT ALL PRIVILEGES ON SCHEMA public TO vuecom;
-- GRANT ALL ON ALL TABLES IN SCHEMA public TO vuecom; 
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_orders

-- GRANT CONNECT ON DATABASE vuecom_orders TO vuecom;
-- GRANT ALL PRIVILEGES ON SCHEMA public TO vuecom;
-- GRANT ALL ON ALL TABLES IN SCHEMA public TO vuecom; 
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_users

-- GRANT CONNECT ON DATABASE vuecom_users TO vuecom;
-- GRANT ALL PRIVILEGES ON SCHEMA public TO vuecom;
-- GRANT ALL ON ALL TABLES IN SCHEMA public TO vuecom; 
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL SEQUENCES IN SCHEMA public to vuecom;
-- GRANT ALL ON ALL FUNCTIONS IN SCHEMA public to vuecom;