\c vuecom_catalog

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;

\c vuecom_inventory

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_orders

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_users

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;
