\c vuecom_catalog

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT CONNECT ON DATABASE vuecom_catalog TO vuecom;
GRANT USAGE, CREATE ON SCHEMA public TO vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;

\c vuecom_inventory

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT CONNECT ON DATABASE vuecom_inventory TO vuecom;
GRANT USAGE, CREATE ON SCHEMA public TO vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_orders

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT CONNECT ON DATABASE vuecom_orders TO vuecom;
GRANT USAGE, CREATE ON SCHEMA public TO vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;


\c vuecom_users

-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to vuecom;
GRANT CONNECT ON DATABASE vuecom_users TO vuecom;
GRANT USAGE, CREATE ON SCHEMA public TO vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL SEQUENCES IN SCHEMA public to vuecom;
GRANT SELECT, UPDATE, INSERT, DELETE ON ALL FUNCTIONS IN SCHEMA public to vuecom;
