package auth

import (
	"github.com/chibx/vuecom/backend/services/gateway/internal/types"

	"github.com/gofiber/fiber/v2"
)

func RegisterRoutes(app fiber.Router, api *types.Api) {
	auth := app.Group("/auth")

	// Check for a signed token in the cookies that would get generated by visiting (GET) the /auth/register/:token
	// This token would be requested as well when trying to manually (forcefully) visit the /register route in the frontend
	auth.Post("/register", Register(api))
	auth.Post("/login", Login(api))
}
